#!/bin/zsh

clear

echo "🖥"
echo "My setup, by @sebacarrasco93"
echo ""

old_git_email="$(git config --global user.email)"
old_git_name=$(git config --global user.name)

while true; do
    if [[ -n "$old_git_email" ]]; then
        echo "1/4: Enter your Git email ($old_git_email):"
    else
        echo "1/4: Enter your Git email"
    fi
    
    read git_email

    git_email="${git_email:-$old_git_email}"

    if [[ -n "$git_email" ]]; then
        break
    else
        echo "Please enter a valid email"
    fi
done

echo "2/4: Enter your Git name ($old_git_name)"
read git_name

git_name="${git_name:-$old_git_name}"

echo "3/4: Enter your SSH identificator for this PC: Example: My Work Mac"
read ssh_identificator

echo "4/4: Generating SSH key with ed25519"
ssh-keygen -t ed25519 -C "$ssh_identificator"

echo "Moving Screenshots to current User folder"
mkdir ~/Screenshots
defaults write com.apple.screencapture location ~/Screenshots

echo "Installing Homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo "Add links to Homebrew"
echo >> /Users/seba/.zprofile
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/seba/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"

echo "Installing formulaes"
brew install git fish node pnpm htop nvim vim mailpit || true

echo "Starting mailpit"
brew services start mailpit

echo "Configuring Git"
git config --global init.defaultBranch main
git config --global user.email "$git_email"
git config --global user.name "$git_name"

echo "Installing casks"
brew install --cask --force telegram google-chrome herd visual-studio-code dbngin raycast iterm2 whatsapp macs-fan-control shottr nrlquaker-winbox sequel-ace tableplus warp postman spotify firefox vlc keka wireshark insomnia monitorcontrol microsoft-edge arduino-ide hot cameracontroller youtube-downloader omnidisksweeper android-file-transfer android-file-transfer imageoptim tiles 4k-video-downloaderplus brave-browser speedtest-cli slack || true

echo "Installing MS Office Apps"
brew install --cask --force microsoft-word microsoft-excel microsoft-powerpoint

echo "Installing Cascadia Code, Jetbrains Mono Nerd, Fira Code fonts"
brew install --cask --force font-cascadia-code font-jetbrains-mono-nerd-font font-fira-code-nerd-font

echo "Installing Operator-Caska font"
git clone https://github.com/Anant-mishra1729/Operator-caska-Font.git
cp -Rf Operator-caska-Font/*.ttf ~/Library/Fonts/
rm -Rf Operator-caska-Font/

echo "Downloading Dvorak Spanish"
curl -Lo ~/Library/Keyboard\ Layouts/Dvorak-Spanish.bundle.zip https://github.com/sebacarrasco93/my-setup/raw/main/extra/Dvorak-Spanish.bundle.zip

echo "Unzip Dvorak Spanish"
unzip -o ~/Library/Keyboard\ Layouts/Dvorak-Spanish.bundle.zip -d ~/Library/Keyboard\ Layouts/

echo "Removing Dvorak Zip file"
rm ~/Library/Keyboard\ Layouts/Dvorak-Spanish.bundle.zip

echo "Finding fish shell location"
set fish_path=$(command -v fish)

echo "Checking if fish shell is correctly installed in order to prevent errors"
if [ -n "$fish_path" ]; then
    eval "echo $fish_path | sudo tee -a /etc/shells"
    eval "chsh -s $fish_path"
fi

curl https://raw.githubusercontent.com/sebacarrasco93/my-setup/main/macOS-fish | fish

echo "Adding Herd to PATH"
echo 'export PATH="$HOME/Library/Application Support/Herd/bin:$PATH"' >> ~/.zshrc
